pokemon('bulbasaur', '001').
pokemon('ivysaur', '002').
pokemon('venusaur', '003').
pokemon('charmander', '004').
pokemon('charmeleon', '005').
pokemon('charizard', '006').
pokemon('squirtle', '007').
pokemon('wartortle', '008').
pokemon('blastoise', '009').
pokemon('caterpie', '010').
pokemon('metapod', '011').
pokemon('butterfree', '012').
pokemon('weedle', '013').
pokemon('kakuna', '014').
pokemon('beedrill', '015').
pokemon('pidgey', '016').
pokemon('pidgeotto', '017').
pokemon('pidgeot', '018').
pokemon('rattata', '019').
pokemon('raticate', '020').
pokemon('spearow', '021').
pokemon('fearow', '022').
pokemon('ekans', '023').
pokemon('arbok', '024').
pokemon('pikachu', '025').
pokemon('raichu', '026').
pokemon('sandshrew', '027').
pokemon('sandslash', '028').
pokemon('nidoran(female)', '029').
pokemon('nidorina', '030').
pokemon('nidoqueen', '031').
pokemon('nidoran(male)', '032').
pokemon('nidorino', '033').
pokemon('nidoking', '034').
pokemon('clefairy', '035').
pokemon('clefable', '036').
pokemon('vulpix', '037').
pokemon('ninetales', '038').
pokemon('jigglypuff', '039').
pokemon('wigglytuff', '040').
pokemon('zubat', '041').
pokemon('golbat', '042').
pokemon('oddish', '043').
pokemon('gloom', '044').
pokemon('vileplume', '045').
pokemon('paras', '046').
pokemon('parasect', '047').
pokemon('venonat', '048').
pokemon('venomoth', '049').
pokemon('diglett', '050').
pokemon('dugtrio', '051').
pokemon('meowth', '052').
pokemon('persian', '053').
pokemon('psyduck', '054').
pokemon('golduck', '055').
pokemon('mankey', '056').
pokemon('primeape', '057').
pokemon('growlithe', '058').
pokemon('arcanine', '059').
pokemon('poliwag', '060').
pokemon('poliwhirl', '061').
pokemon('poliwrath', '062').
pokemon('abra', '063').
pokemon('kadabra', '064').
pokemon('alakazam', '065').
pokemon('machop', '066').
pokemon('machoke', '067').
pokemon('machamp', '068').
pokemon('bellsprout', '069').
pokemon('weepinbell', '070').
pokemon('victreebel', '071').
pokemon('tentacool', '072').
pokemon('tentacruel', '073').
pokemon('geodude', '074').
pokemon('graveler', '075').
pokemon('golem', '076').
pokemon('ponyta', '077').
pokemon('rapidash', '078').
pokemon('slowpoke', '079').
pokemon('slowbro', '080').
pokemon('magnemite', '081').
pokemon('magneton', '082').
pokemon('farfetchd', '083').
pokemon('doduo', '084').
pokemon('dodrio', '085').
pokemon('seel', '086').
pokemon('dewgong', '087').
pokemon('grimer', '088').
pokemon('muk', '089').
pokemon('shellder', '090').
pokemon('cloyster', '091').
pokemon('gastly', '092').
pokemon('haunter', '093').
pokemon('gengar', '094').
pokemon('onix', '095').
pokemon('drowzee', '096').
pokemon('hypno', '097').
pokemon('krabby', '098').
pokemon('kingler', '099').
pokemon('voltorb', '100').
pokemon('electrode', '101').
pokemon('exeggcute', '102').
pokemon('exeggutor', '103').
pokemon('cubone', '104').
pokemon('marowak', '105').
pokemon('hitmonlee', '106').
pokemon('hitmonchan', '107').
pokemon('lickitung', '108').
pokemon('koffing', '109').
pokemon('weezing', '110').
pokemon('rhyhorn', '111').
pokemon('rhydon', '112').
pokemon('chansey', '113').
pokemon('tangela', '114').
pokemon('kangaskhan', '115').
pokemon('horsea', '116').
pokemon('seadra', '117').
pokemon('goldeen', '118').
pokemon('seaking', '119').
pokemon('staryu', '120').
pokemon('starmie', '121').
pokemon('mr. mime', '122').
pokemon('scyther', '123').
pokemon('jynx', '124').
pokemon('electabuzz', '125').
pokemon('magmar', '126').
pokemon('pinsir', '127').
pokemon('tauros', '128').
pokemon('magikarp', '129').
pokemon('gyarados', '130').
pokemon('lapras', '131').
pokemon('ditto', '132').
pokemon('eevee', '133').
pokemon('vaporeon', '134').
pokemon('jolteon', '135').
pokemon('flareon', '136').
pokemon('porygon', '137').
pokemon('omanyte', '138').
pokemon('omastar', '139').
pokemon('kabuto', '140').
pokemon('kabutops', '141').
pokemon('aerodactyl', '142').
pokemon('snorlax', '143').
pokemon('articuno', '144').
pokemon('zapdos', '145').
pokemon('moltres', '146').
pokemon('dratini', '147').
pokemon('dragonair', '148').
pokemon('dragonite', '149').
pokemon('mewtwo', '150').
pokemon('mew', '151').

type('bulbasaur', 'grass').
type('bulbasaur', 'poison').
type('ivysaur', 'grass').
type('ivysaur', 'poison').
type('venusaur', 'grass').
type('venusaur', 'poison').
type('charmander', 'fire').
type('charmeleon', 'fire').
type('charizard', 'fire').
type('charizard', 'flying').
type('squirtle', 'water').
type('wartortle', 'water').
type('blastoise', 'water').
type('caterpie', 'bug').
type('metapod', 'bug').
type('butterfree', 'bug').
type('butterfree', 'flying').
type('weedle', 'bug').
type('weedle', 'poison').
type('kakuna', 'bug').
type('kakuna', 'poison').
type('beedrill', 'bug').
type('beedrill', 'poison').
type('pidgey', 'normal').
type('pidgey', 'flying').
type('pidgeotto', 'normal').
type('pidgeotto', 'flying').
type('pidgeot', 'normal').
type('pidgeot', 'flying').
type('rattata', 'normal').
type('raticate', 'normal').
type('spearow', 'normal').
type('spearow', 'flying').
type('fearow', 'normal').
type('fearow', 'flying').
type('ekans', 'poison').
type('arbok', 'poison').
type('pikachu', 'electric').
type('raichu', 'electric').
type('sandshrew', 'ground').
type('sandslash', 'ground').
type('nidoran(female)', 'poison').
type('nidorina', 'poison').
type('nidoqueen', 'poison').
type('nidoqueen', 'ground').
type('nidoran(male)', 'poison').
type('nidorino', 'poison').
type('nidoking', 'poison').
type('nidoking', 'ground').
type('clefairy', 'normal').
type('clefable', 'normal').
type('vulpix', 'fire').
type('ninetales', 'fire').
type('jigglypuff', 'normal').
type('wigglytuff', 'normal').
type('zubat', 'poison').
type('zubat', 'flying').
type('golbat', 'poison').
type('golbat', 'flying').
type('oddish', 'grass').
type('oddish', 'poison').
type('gloom', 'grass').
type('gloom', 'poison').
type('vileplume', 'grass').
type('vileplume', 'poison').
type('paras', 'bug').
type('paras', 'grass').
type('parasect', 'bug').
type('parasect', 'grass').
type('venonat', 'bug').
type('venonat', 'poison').
type('venomoth', 'bug').
type('venomoth', 'poison').
type('diglett', 'ground').
type('dugtrio', 'ground').
type('meowth', 'normal').
type('persian', 'normal').
type('psyduck', 'water').
type('golduck', 'water').
type('mankey', 'fighting').
type('primeape', 'fighting').
type('growlithe', 'fire').
type('arcanine', 'fire').
type('poliwag', 'water').
type('poliwhirl', 'water').
type('poliwrath', 'water').
type('poliwrath', 'fighting').
type('abra', 'psychic').
type('kadabra', 'psychic').
type('alakazam', 'psychic').
type('machop', 'fighting').
type('machoke', 'fighting').
type('machamp', 'fighting').
type('bellsprout', 'grass').
type('bellsprout', 'poison').
type('weepinbell', 'grass').
type('weepinbell', 'poison').
type('victreebel', 'grass').
type('victreebel', 'poison').
type('tentacool', 'water').
type('tentacool', 'poison').
type('tentacruel', 'water').
type('tentacruel', 'poison').
type('geodude', 'rock').
type('geodude', 'ground').
type('graveler', 'rock').
type('graveler', 'ground').
type('golem', 'rock').
type('golem', 'ground').
type('ponyta', 'fire').
type('rapidash', 'fire').
type('slowpoke', 'water').
type('slowpoke', 'psychic').
type('slowbro', 'water').
type('slowbro', 'psychic').
type('magnemite', 'electric').
type('magneton', 'electric').
type('farfetchd', 'normal').
type('farfetchd', 'flying').
type('doduo', 'normal').
type('doduo', 'flying').
type('dodrio', 'normal').
type('dodrio', 'flying').
type('seel', 'water').
type('dewgong', 'water').
type('dewgong', 'ice').
type('grimer', 'poison').
type('muk', 'poison').
type('shellder', 'water').
type('cloyster', 'water').
type('cloyster', 'ice').
type('gastly', 'ghost').
type('gastly', 'poison').
type('haunter', 'ghost').
type('haunter', 'poison').
type('gengar', 'ghost').
type('gengar', 'poison').
type('onix', 'rock').
type('onix', 'ground').
type('drowzee', 'psychic').
type('hypno', 'psychic').
type('krabby', 'water').
type('kingler', 'water').
type('voltorb', 'electric').
type('electrode', 'electric').
type('exeggcute', 'grass').
type('exeggcute', 'psychic').
type('exeggutor', 'grass').
type('exeggutor', 'psychic').
type('cubone', 'ground').
type('marowak', 'ground').
type('hitmonlee', 'fighting').
type('hitmonchan', 'fighting').
type('lickitung', 'normal').
type('koffing', 'poison').
type('weezing', 'poison').
type('rhyhorn', 'ground').
type('rhyhorn', 'rock').
type('rhydon', 'ground').
type('rhydon', 'rock').
type('chansey', 'normal').
type('tangela', 'grass').
type('kangaskhan', 'normal').
type('horsea', 'water').
type('seadra', 'water').
type('goldeen', 'water').
type('seaking', 'water').
type('staryu', 'water').
type('starmie', 'water').
type('starmie', 'psychic').
type('mr. mime', 'psychic').
type('scyther', 'bug').
type('scyther', 'flying').
type('jynx', 'ice').
type('jynx', 'psychic').
type('electabuzz', 'electric').
type('magmar', 'fire').
type('pinsir', 'bug').
type('tauros', 'normal').
type('magikarp', 'water').
type('gyarados', 'water').
type('gyarados', 'flying').
type('lapras', 'water').
type('lapras', 'ice').
type('ditto', 'normal').
type('eevee', 'normal').
type('vaporeon', 'water').
type('jolteon', 'electric').
type('flareon', 'fire').
type('porygon', 'normal').
type('omanyte', 'rock').
type('omanyte', 'water').
type('omastar', 'rock').
type('omastar', 'water').
type('kabuto', 'rock').
type('kabuto', 'water').
type('kabutops', 'rock').
type('kabutops', 'water').
type('aerodactyl', 'rock').
type('aerodactyl', 'flying').
type('snorlax', 'normal').
type('articuno', 'ice').
type('articuno', 'flying').
type('zapdos', 'electric').
type('zapdos', 'flying').
type('moltres', 'fire').
type('moltres', 'flying').
type('dratini', 'dragon').
type('dragonair', 'dragon').
type('dragonite', 'dragon').
type('dragonite', 'flying').
type('mewtwo', 'psychic').
type('mew', 'psychic').

height('bulbasaur', 0.71).
height('ivysaur', 0.99).
height('venusaur', 2.01).
height('charmander', 0.61).
height('charmeleon', 1.09).
height('charizard', 1.70).
height('squirtle', 0.51).
height('wartortle', 0.99).
height('blastoise', 1.60).
height('caterpie', 0.30).
height('metapod', 0.71).
height('butterfree', 1.09).
height('weedle', 0.30).
height('kakuna', 0.61).
height('beedrill', 0.99).
height('pidgey', 0.30).
height('pidgeotto', 1.09).
height('pidgeot', 1.50).
height('rattata', 0.30).
height('raticate', 0.71).
height('spearow', 0.30).
height('fearow', 1.19).
height('ekans', 2.01).
height('arbok', 3.51).
height('pikachu', 0.41).
height('raichu', 0.79).
height('sandshrew', 0.61).
height('sandslash', 0.99).
height('nidoran(female)', 0.41).
height('nidorina', 0.79).
height('nidoqueen', 1.30).
height('nidoran(male)', 0.51).
height('nidorino', 0.89).
height('nidoking', 1.40).
height('clefairy', 0.61).
height('clefable', 1.30).
height('vulpix', 0.61).
height('ninetales', 1.09).
height('jigglypuff', 0.51).
height('wigglytuff', 0.99).
height('zubat', 0.79).
height('golbat', 1.60).
height('oddish', 0.51).
height('gloom', 0.79).
height('vileplume', 1.19).
height('paras', 0.30).
height('parasect', 0.99).
height('venonat', 0.99).
height('venomoth', 1.50).
height('diglett', 0.20).
height('dugtrio', 0.71).
height('meowth', 0.41).
height('persian', 0.99).
height('psyduck', 0.79).
height('golduck', 1.70).
height('mankey', 0.51).
height('primeape', 0.99).
height('growlithe', 0.71).
height('arcanine', 1.91).
height('poliwag', 0.61).
height('poliwhirl', 0.99).
height('poliwrath', 1.30).
height('abra', 0.89).
height('kadabra', 1.30).
height('alakazam', 1.50).
height('machop', 0.79).
height('machoke', 1.50).
height('machamp', 1.60).
height('bellsprout', 0.71).
height('weepinbell', 0.99).
height('victreebel', 1.70).
height('tentacool', 0.89).
height('tentacruel', 1.60).
height('geodude', 0.41).
height('graveler', 0.99).
height('golem', 1.40).
height('ponyta', 0.99).
height('rapidash', 1.70).
height('slowpoke', 1.19).
height('slowbro', 1.60).
height('magnemite', 0.30).
height('magneton', 0.99).
height('farfetchd', 0.79).
height('doduo', 1.40).
height('dodrio', 1.80).
height('seel', 1.09).
height('dewgong', 1.70).
height('grimer', 0.89).
height('muk', 1.19).
height('shellder', 0.30).
height('cloyster', 1.50).
height('gastly', 1.30).
height('haunter', 1.60).
height('gengar', 1.50).
height('onix', 8.79).
height('drowzee', 0.99).
height('hypno', 1.60).
height('krabby', 0.41).
height('kingler', 1.30).
height('voltorb', 0.51).
height('electrode', 1.19).
height('exeggcute', 0.41).
height('exeggutor', 2.01).
height('cubone', 0.41).
height('marowak', 0.99).
height('hitmonlee', 1.50).
height('hitmonchan', 1.40).
height('lickitung', 1.19).
height('koffing', 0.61).
height('weezing', 1.19).
height('rhyhorn', 0.99).
height('rhydon', 1.91).
height('chansey', 1.09).
height('tangela', 0.99).
height('kangaskhan', 2.21).
height('horsea', 0.41).
height('seadra', 1.19).
height('goldeen', 0.61).
height('seaking', 1.30).
height('staryu', 0.79).
height('starmie', 1.09).
height('mr. mime', 1.30).
height('scyther', 1.50).
height('jynx', 1.40).
height('electabuzz', 1.09).
height('magmar', 1.30).
height('pinsir', 1.50).
height('tauros', 1.40).
height('magikarp', 0.89).
height('gyarados', 6.50).
height('lapras', 2.49).
height('ditto', 0.30).
height('eevee', 0.30).
height('vaporeon', 0.99).
height('jolteon', 0.79).
height('flareon', 0.89).
height('porygon', 0.79).
height('omanyte', 0.41).
height('omastar', 0.99).
height('kabuto', 0.51).
height('kabutops', 1.30).
height('aerodactyl', 1.80).
height('snorlax', 2.11).
height('articuno', 1.70).
height('zapdos', 1.60).
height('moltres', 2.01).
height('dratini', 1.80).
height('dragonair', 3.99).
height('dragonite', 2.21).
height('mewtwo', 2.01).
height('mew', 0.41).

weight('bulbasaur', 6.9).
weight('ivysaur', 13.0).
weight('venusaur', 100.0).
weight('charmander', 8.5).
weight('charmeleon', 19.0).
weight('charizard', 90.5).
weight('squirtle', 9.0).
weight('wartortle', 22.5).
weight('blastoise', 85.5).
weight('caterpie', 2.9).
weight('metapod', 9.9).
weight('butterfree', 32.0).
weight('weedle', 3.2).
weight('kakuna', 10.0).
weight('beedrill', 29.5).
weight('pidgey', 1.8).
weight('pidgeotto', 30.0).
weight('pidgeot', 39.5).
weight('rattata', 3.5).
weight('raticate', 18.5).
weight('spearow', 2.0).
weight('fearow', 38.0).
weight('ekans', 6.9).
weight('arbok', 65.0).
weight('pikachu', 6.0).
weight('raichu', 30.0).
weight('sandshrew', 12.0).
weight('sandslash', 29.5).
weight('nidoran(female)', 7.0).
weight('nidorina', 20.0).
weight('nidoqueen', 60.0).
weight('nidoran(male)', 9.0).
weight('nidorino', 19.5).
weight('nidoking', 62.0).
weight('clefairy', 7.5).
weight('clefable', 40.0).
weight('vulpix', 9.9).
weight('ninetales', 19.9).
weight('jigglypuff', 5.5).
weight('wigglytuff', 12.0).
weight('zubat', 7.5).
weight('golbat', 55.0).
weight('oddish', 5.4).
weight('gloom', 8.6).
weight('vileplume', 18.6).
weight('paras', 5.4).
weight('parasect', 29.5).
weight('venonat', 30.0).
weight('venomoth', 12.5).
weight('diglett', 0.8).
weight('dugtrio', 33.3).
weight('meowth', 4.2).
weight('persian', 32.0).
weight('psyduck', 19.6).
weight('golduck', 76.6).
weight('mankey', 28.0).
weight('primeape', 32.0).
weight('growlithe', 19.0).
weight('arcanine', 155.0).
weight('poliwag', 12.4).
weight('poliwhirl', 20.0).
weight('poliwrath', 54.0).
weight('abra', 19.5).
weight('kadabra', 56.5).
weight('alakazam', 48.0).
weight('machop', 19.5).
weight('machoke', 70.5).
weight('machamp', 130.0).
weight('bellsprout', 4.0).
weight('weepinbell', 6.4).
weight('victreebel', 15.5).
weight('tentacool', 45.5).
weight('tentacruel', 55.0).
weight('geodude', 20.0).
weight('graveler', 105.0).
weight('golem', 300.0).
weight('ponyta', 30.0).
weight('rapidash', 95.0).
weight('slowpoke', 36.0).
weight('slowbro', 78.5).
weight('magnemite', 6.0).
weight('magneton', 60.0).
weight('farfetchd', 15.0).
weight('doduo', 39.2).
weight('dodrio', 85.2).
weight('seel', 90.0).
weight('dewgong', 120.0).
weight('grimer', 30.0).
weight('muk', 30.0).
weight('shellder', 4.0).
weight('cloyster', 132.5).
weight('gastly', 0.1).
weight('haunter', 0.1).
weight('gengar', 40.5).
weight('onix', 210.0).
weight('drowzee', 32.4).
weight('hypno', 75.6).
weight('krabby', 6.5).
weight('kingler', 60.0).
weight('voltorb', 10.4).
weight('electrode', 66.6).
weight('exeggcute', 2.5).
weight('exeggutor', 120.0).
weight('cubone', 6.5).
weight('marowak', 45.0).
weight('hitmonlee', 49.8).
weight('hitmonchan', 50.2).
weight('lickitung', 65.5).
weight('koffing', 1.0).
weight('weezing', 9.5).
weight('rhyhorn', 115.0).
weight('rhydon', 120.0).
weight('chansey', 34.6).
weight('tangela', 35.0).
weight('kangaskhan', 80.0).
weight('horsea', 8.0).
weight('seadra', 25.0).
weight('goldeen', 15.0).
weight('seaking', 39.0).
weight('staryu', 34.5).
weight('starmie', 80.0).
weight('mr. mime', 54.5).
weight('scyther', 56.0).
weight('jynx', 40.6).
weight('electabuzz', 30.0).
weight('magmar', 44.5).
weight('pinsir', 55.0).
weight('tauros', 88.4).
weight('magikarp', 10.0).
weight('gyarados', 235.0).
weight('lapras', 220.0).
weight('ditto', 4.0).
weight('eevee', 6.5).
weight('vaporeon', 29.0).
weight('jolteon', 24.5).
weight('flareon', 25.0).
weight('porygon', 36.5).
weight('omanyte', 7.5).
weight('omastar', 35.0).
weight('kabuto', 11.5).
weight('kabutops', 40.5).
weight('aerodactyl', 59.0).
weight('snorlax', 460.0).
weight('articuno', 55.4).
weight('zapdos', 52.6).
weight('moltres', 60.0).
weight('dratini', 3.3).
weight('dragonair', 16.5).
weight('dragonite', 210.0).
weight('mewtwo', 122.0).
weight('mew', 4.0).

next_evolution('bulbasaur', 'ivysaur').
next_evolution('bulbasaur', 'venusaur').
next_evolution('ivysaur', 'venusaur').
next_evolution('charmander', 'charmeleon').
next_evolution('charmander', 'charizard').
next_evolution('charmeleon', 'charizard').
next_evolution('squirtle', 'wartortle').
next_evolution('squirtle', 'blastoise').
next_evolution('wartortle', 'blastoise').
next_evolution('caterpie', 'metapod').
next_evolution('caterpie', 'butterfree').
next_evolution('metapod', 'butterfree').
next_evolution('weedle', 'kakuna').
next_evolution('weedle', 'beedrill').
next_evolution('kakuna', 'beedrill').
next_evolution('pidgey', 'pidgeotto').
next_evolution('pidgey', 'pidgeot').
next_evolution('pidgeotto', 'pidgeot').
next_evolution('rattata', 'raticate').
next_evolution('spearow', 'fearow').
next_evolution('ekans', 'arbok').
next_evolution('pikachu', 'raichu').
next_evolution('sandshrew', 'sandslash').
next_evolution('nidoran(female)', 'nidorina').
next_evolution('nidoran(female)', 'nidoqueen').
next_evolution('nidorina', 'nidoqueen').
next_evolution('nidoran(male)', 'nidorino').
next_evolution('nidoran(male)', 'nidoking').
next_evolution('nidorino', 'nidoking').
next_evolution('clefairy', 'clefable').
next_evolution('vulpix', 'ninetales').
next_evolution('jigglypuff', 'wigglytuff').
next_evolution('zubat', 'golbat').
next_evolution('oddish', 'gloom').
next_evolution('oddish', 'vileplume').
next_evolution('gloom', 'vileplume').
next_evolution('paras', 'parasect').
next_evolution('venonat', 'venomoth').
next_evolution('diglett', 'dugtrio').
next_evolution('meowth', 'persian').
next_evolution('psyduck', 'golduck').
next_evolution('mankey', 'primeape').
next_evolution('growlithe', 'arcanine').
next_evolution('poliwag', 'poliwhirl').
next_evolution('poliwag', 'poliwrath').
next_evolution('poliwhirl', 'poliwrath').
next_evolution('abra', 'kadabra').
next_evolution('abra', 'alakazam').
next_evolution('kadabra', 'alakazam').
next_evolution('machop', 'machoke').
next_evolution('machop', 'machamp').
next_evolution('machoke', 'machamp').
next_evolution('bellsprout', 'weepinbell').
next_evolution('bellsprout', 'victreebel').
next_evolution('weepinbell', 'victreebel').
next_evolution('tentacool', 'tentacruel').
next_evolution('geodude', 'graveler').
next_evolution('geodude', 'golem').
next_evolution('graveler', 'golem').
next_evolution('ponyta', 'rapidash').
next_evolution('slowpoke', 'slowbro').
next_evolution('magnemite', 'magneton').
next_evolution('doduo', 'dodrio').
next_evolution('seel', 'dewgong').
next_evolution('grimer', 'muk').
next_evolution('shellder', 'cloyster').
next_evolution('gastly', 'haunter').
next_evolution('gastly', 'gengar').
next_evolution('haunter', 'gengar').
next_evolution('drowzee', 'hypno').
next_evolution('krabby', 'kingler').
next_evolution('voltorb', 'electrode').
next_evolution('exeggcute', 'exeggutor').
next_evolution('cubone', 'marowak').
next_evolution('koffing', 'weezing').
next_evolution('rhyhorn', 'rhydon').
next_evolution('horsea', 'seadra').
next_evolution('goldeen', 'seaking').
next_evolution('staryu', 'starmie').
next_evolution('magikarp', 'gyarados').
next_evolution('eevee', 'vaporeon').
next_evolution('eevee', 'jolteon').
next_evolution('eevee', 'flareon').
next_evolution('omanyte', 'omastar').
next_evolution('kabuto', 'kabutops').
next_evolution('dratini', 'dragonair').
next_evolution('dratini', 'dragonite').
next_evolution('dragonair', 'dragonite').

prev_evolution('ivysaur', 'bulbasaur').
prev_evolution('venusaur', 'bulbasaur').
prev_evolution('venusaur', 'ivysaur').
prev_evolution('charmeleon', 'charmander').
prev_evolution('charizard', 'charmander').
prev_evolution('charizard', 'charmeleon').
prev_evolution('wartortle', 'squirtle').
prev_evolution('blastoise', 'squirtle').
prev_evolution('blastoise', 'wartortle').
prev_evolution('metapod', 'caterpie').
prev_evolution('butterfree', 'caterpie').
prev_evolution('butterfree', 'metapod').
prev_evolution('kakuna', 'weedle').
prev_evolution('beedrill', 'weedle').
prev_evolution('beedrill', 'kakuna').
prev_evolution('pidgeotto', 'pidgey').
prev_evolution('pidgeot', 'pidgey').
prev_evolution('pidgeot', 'pidgeotto').
prev_evolution('raticate', 'rattata').
prev_evolution('fearow', 'spearow').
prev_evolution('arbok', 'ekans').
prev_evolution('raichu', 'pikachu').
prev_evolution('sandslash', 'sandshrew').
prev_evolution('nidorina', 'nidoran(female)').
prev_evolution('nidoqueen', 'nidoran(female)').
prev_evolution('nidoqueen', 'nidorina').
prev_evolution('nidorino', 'nidoran(male)').
prev_evolution('nidoking', 'nidoran(male)').
prev_evolution('nidoking', 'nidorino').
prev_evolution('clefable', 'clefairy').
prev_evolution('ninetales', 'vulpix').
prev_evolution('wigglytuff', 'jigglypuff').
prev_evolution('golbat', 'zubat').
prev_evolution('gloom', 'oddish').
prev_evolution('vileplume', 'oddish').
prev_evolution('vileplume', 'gloom').
prev_evolution('parasect', 'paras').
prev_evolution('venomoth', 'venonat').
prev_evolution('dugtrio', 'diglett').
prev_evolution('persian', 'meowth').
prev_evolution('golduck', 'psyduck').
prev_evolution('primeape', 'mankey').
prev_evolution('arcanine', 'growlithe').
prev_evolution('poliwhirl', 'poliwag').
prev_evolution('poliwrath', 'poliwag').
prev_evolution('poliwrath', 'poliwhirl').
prev_evolution('kadabra', 'abra').
prev_evolution('alakazam', 'abra').
prev_evolution('alakazam', 'kadabra').
prev_evolution('machoke', 'machop').
prev_evolution('machamp', 'machop').
prev_evolution('machamp', 'machoke').
prev_evolution('weepinbell', 'bellsprout').
prev_evolution('victreebel', 'bellsprout').
prev_evolution('victreebel', 'weepinbell').
prev_evolution('tentacruel', 'tentacool').
prev_evolution('graveler', 'geodude').
prev_evolution('golem', 'geodude').
prev_evolution('golem', 'graveler').
prev_evolution('rapidash', 'ponyta').
prev_evolution('slowbro', 'slowpoke').
prev_evolution('magneton', 'magnemite').
prev_evolution('dodrio', 'doduo').
prev_evolution('dewgong', 'seel').
prev_evolution('muk', 'grimer').
prev_evolution('cloyster', 'shellder').
prev_evolution('haunter', 'gastly').
prev_evolution('gengar', 'gastly').
prev_evolution('gengar', 'haunter').
prev_evolution('hypno', 'drowzee').
prev_evolution('kingler', 'krabby').
prev_evolution('electrode', 'voltorb').
prev_evolution('exeggutor', 'exeggcute').
prev_evolution('marowak', 'cubone').
prev_evolution('weezing', 'koffing').
prev_evolution('rhydon', 'rhyhorn').
prev_evolution('seadra', 'horsea').
prev_evolution('seaking', 'goldeen').
prev_evolution('starmie', 'staryu').
prev_evolution('gyarados', 'magikarp').
prev_evolution('vaporeon', 'eevee').
prev_evolution('jolteon', 'eevee').
prev_evolution('flareon', 'eevee').
prev_evolution('omastar', 'omanyte').
prev_evolution('kabutops', 'kabuto').
prev_evolution('dragonair', 'dratini').
prev_evolution('dragonite', 'dratini').
prev_evolution('dragonite', 'dragonair').

image('bulbasaur', 'http://www.serebii.net/pokemongo/pokemon/001.png').
image('ivysaur', 'http://www.serebii.net/pokemongo/pokemon/002.png').
image('venusaur', 'http://www.serebii.net/pokemongo/pokemon/003.png').
image('charmander', 'http://www.serebii.net/pokemongo/pokemon/004.png').
image('charmeleon', 'http://www.serebii.net/pokemongo/pokemon/005.png').
image('charizard', 'http://www.serebii.net/pokemongo/pokemon/006.png').
image('squirtle', 'http://www.serebii.net/pokemongo/pokemon/007.png').
image('wartortle', 'http://www.serebii.net/pokemongo/pokemon/008.png').
image('blastoise', 'http://www.serebii.net/pokemongo/pokemon/009.png').
image('caterpie', 'http://www.serebii.net/pokemongo/pokemon/010.png').
image('metapod', 'http://www.serebii.net/pokemongo/pokemon/011.png').
image('butterfree', 'http://www.serebii.net/pokemongo/pokemon/012.png').
image('weedle', 'http://www.serebii.net/pokemongo/pokemon/013.png').
image('kakuna', 'http://www.serebii.net/pokemongo/pokemon/014.png').
image('beedrill', 'http://www.serebii.net/pokemongo/pokemon/015.png').
image('pidgey', 'http://www.serebii.net/pokemongo/pokemon/016.png').
image('pidgeotto', 'http://www.serebii.net/pokemongo/pokemon/017.png').
image('pidgeot', 'http://www.serebii.net/pokemongo/pokemon/018.png').
image('rattata', 'http://www.serebii.net/pokemongo/pokemon/019.png').
image('raticate', 'http://www.serebii.net/pokemongo/pokemon/020.png').
image('spearow', 'http://www.serebii.net/pokemongo/pokemon/021.png').
image('fearow', 'http://www.serebii.net/pokemongo/pokemon/022.png').
image('ekans', 'http://www.serebii.net/pokemongo/pokemon/023.png').
image('arbok', 'http://www.serebii.net/pokemongo/pokemon/024.png').
image('pikachu', 'http://www.serebii.net/pokemongo/pokemon/025.png').
image('raichu', 'http://www.serebii.net/pokemongo/pokemon/026.png').
image('sandshrew', 'http://www.serebii.net/pokemongo/pokemon/027.png').
image('sandslash', 'http://www.serebii.net/pokemongo/pokemon/028.png').
image('nidoran(female)', 'http://www.serebii.net/pokemongo/pokemon/029.png').
image('nidorina', 'http://www.serebii.net/pokemongo/pokemon/030.png').
image('nidoqueen', 'http://www.serebii.net/pokemongo/pokemon/031.png').
image('nidoran(male)', 'http://www.serebii.net/pokemongo/pokemon/032.png').
image('nidorino', 'http://www.serebii.net/pokemongo/pokemon/033.png').
image('nidoking', 'http://www.serebii.net/pokemongo/pokemon/034.png').
image('clefairy', 'http://www.serebii.net/pokemongo/pokemon/035.png').
image('clefable', 'http://www.serebii.net/pokemongo/pokemon/036.png').
image('vulpix', 'http://www.serebii.net/pokemongo/pokemon/037.png').
image('ninetales', 'http://www.serebii.net/pokemongo/pokemon/038.png').
image('jigglypuff', 'http://www.serebii.net/pokemongo/pokemon/039.png').
image('wigglytuff', 'http://www.serebii.net/pokemongo/pokemon/040.png').
image('zubat', 'http://www.serebii.net/pokemongo/pokemon/041.png').
image('golbat', 'http://www.serebii.net/pokemongo/pokemon/042.png').
image('oddish', 'http://www.serebii.net/pokemongo/pokemon/043.png').
image('gloom', 'http://www.serebii.net/pokemongo/pokemon/044.png').
image('vileplume', 'http://www.serebii.net/pokemongo/pokemon/045.png').
image('paras', 'http://www.serebii.net/pokemongo/pokemon/046.png').
image('parasect', 'http://www.serebii.net/pokemongo/pokemon/047.png').
image('venonat', 'http://www.serebii.net/pokemongo/pokemon/048.png').
image('venomoth', 'http://www.serebii.net/pokemongo/pokemon/049.png').
image('diglett', 'http://www.serebii.net/pokemongo/pokemon/050.png').
image('dugtrio', 'http://www.serebii.net/pokemongo/pokemon/051.png').
image('meowth', 'http://www.serebii.net/pokemongo/pokemon/052.png').
image('persian', 'http://www.serebii.net/pokemongo/pokemon/053.png').
image('psyduck', 'http://www.serebii.net/pokemongo/pokemon/054.png').
image('golduck', 'http://www.serebii.net/pokemongo/pokemon/055.png').
image('mankey', 'http://www.serebii.net/pokemongo/pokemon/056.png').
image('primeape', 'http://www.serebii.net/pokemongo/pokemon/057.png').
image('growlithe', 'http://www.serebii.net/pokemongo/pokemon/058.png').
image('arcanine', 'http://www.serebii.net/pokemongo/pokemon/059.png').
image('poliwag', 'http://www.serebii.net/pokemongo/pokemon/060.png').
image('poliwhirl', 'http://www.serebii.net/pokemongo/pokemon/061.png').
image('poliwrath', 'http://www.serebii.net/pokemongo/pokemon/062.png').
image('abra', 'http://www.serebii.net/pokemongo/pokemon/063.png').
image('kadabra', 'http://www.serebii.net/pokemongo/pokemon/064.png').
image('alakazam', 'http://www.serebii.net/pokemongo/pokemon/065.png').
image('machop', 'http://www.serebii.net/pokemongo/pokemon/066.png').
image('machoke', 'http://www.serebii.net/pokemongo/pokemon/067.png').
image('machamp', 'http://www.serebii.net/pokemongo/pokemon/068.png').
image('bellsprout', 'http://www.serebii.net/pokemongo/pokemon/069.png').
image('weepinbell', 'http://www.serebii.net/pokemongo/pokemon/070.png').
image('victreebel', 'http://www.serebii.net/pokemongo/pokemon/071.png').
image('tentacool', 'http://www.serebii.net/pokemongo/pokemon/072.png').
image('tentacruel', 'http://www.serebii.net/pokemongo/pokemon/073.png').
image('geodude', 'http://www.serebii.net/pokemongo/pokemon/074.png').
image('graveler', 'http://www.serebii.net/pokemongo/pokemon/075.png').
image('golem', 'http://www.serebii.net/pokemongo/pokemon/076.png').
image('ponyta', 'http://www.serebii.net/pokemongo/pokemon/077.png').
image('rapidash', 'http://www.serebii.net/pokemongo/pokemon/078.png').
image('slowpoke', 'http://www.serebii.net/pokemongo/pokemon/079.png').
image('slowbro', 'http://www.serebii.net/pokemongo/pokemon/080.png').
image('magnemite', 'http://www.serebii.net/pokemongo/pokemon/081.png').
image('magneton', 'http://www.serebii.net/pokemongo/pokemon/082.png').
image('farfetchd', 'http://www.serebii.net/pokemongo/pokemon/083.png').
image('doduo', 'http://www.serebii.net/pokemongo/pokemon/084.png').
image('dodrio', 'http://www.serebii.net/pokemongo/pokemon/085.png').
image('seel', 'http://www.serebii.net/pokemongo/pokemon/086.png').
image('dewgong', 'http://www.serebii.net/pokemongo/pokemon/087.png').
image('grimer', 'http://www.serebii.net/pokemongo/pokemon/088.png').
image('muk', 'http://www.serebii.net/pokemongo/pokemon/089.png').
image('shellder', 'http://www.serebii.net/pokemongo/pokemon/090.png').
image('cloyster', 'http://www.serebii.net/pokemongo/pokemon/091.png').
image('gastly', 'http://www.serebii.net/pokemongo/pokemon/092.png').
image('haunter', 'http://www.serebii.net/pokemongo/pokemon/093.png').
image('gengar', 'http://www.serebii.net/pokemongo/pokemon/094.png').
image('onix', 'http://www.serebii.net/pokemongo/pokemon/095.png').
image('drowzee', 'http://www.serebii.net/pokemongo/pokemon/096.png').
image('hypno', 'http://www.serebii.net/pokemongo/pokemon/097.png').
image('krabby', 'http://www.serebii.net/pokemongo/pokemon/098.png').
image('kingler', 'http://www.serebii.net/pokemongo/pokemon/099.png').
image('voltorb', 'http://www.serebii.net/pokemongo/pokemon/100.png').
image('electrode', 'http://www.serebii.net/pokemongo/pokemon/101.png').
image('exeggcute', 'http://www.serebii.net/pokemongo/pokemon/102.png').
image('exeggutor', 'http://www.serebii.net/pokemongo/pokemon/103.png').
image('cubone', 'http://www.serebii.net/pokemongo/pokemon/104.png').
image('marowak', 'http://www.serebii.net/pokemongo/pokemon/105.png').
image('hitmonlee', 'http://www.serebii.net/pokemongo/pokemon/106.png').
image('hitmonchan', 'http://www.serebii.net/pokemongo/pokemon/107.png').
image('lickitung', 'http://www.serebii.net/pokemongo/pokemon/108.png').
image('koffing', 'http://www.serebii.net/pokemongo/pokemon/109.png').
image('weezing', 'http://www.serebii.net/pokemongo/pokemon/110.png').
image('rhyhorn', 'http://www.serebii.net/pokemongo/pokemon/111.png').
image('rhydon', 'http://www.serebii.net/pokemongo/pokemon/112.png').
image('chansey', 'http://www.serebii.net/pokemongo/pokemon/113.png').
image('tangela', 'http://www.serebii.net/pokemongo/pokemon/114.png').
image('kangaskhan', 'http://www.serebii.net/pokemongo/pokemon/115.png').
image('horsea', 'http://www.serebii.net/pokemongo/pokemon/116.png').
image('seadra', 'http://www.serebii.net/pokemongo/pokemon/117.png').
image('goldeen', 'http://www.serebii.net/pokemongo/pokemon/118.png').
image('seaking', 'http://www.serebii.net/pokemongo/pokemon/119.png').
image('staryu', 'http://www.serebii.net/pokemongo/pokemon/120.png').
image('starmie', 'http://www.serebii.net/pokemongo/pokemon/121.png').
image('mr. mime', 'http://www.serebii.net/pokemongo/pokemon/122.png').
image('scyther', 'http://www.serebii.net/pokemongo/pokemon/123.png').
image('jynx', 'http://www.serebii.net/pokemongo/pokemon/124.png').
image('electabuzz', 'http://www.serebii.net/pokemongo/pokemon/125.png').
image('magmar', 'http://www.serebii.net/pokemongo/pokemon/126.png').
image('pinsir', 'http://www.serebii.net/pokemongo/pokemon/127.png').
image('tauros', 'http://www.serebii.net/pokemongo/pokemon/128.png').
image('magikarp', 'http://www.serebii.net/pokemongo/pokemon/129.png').
image('gyarados', 'http://www.serebii.net/pokemongo/pokemon/130.png').
image('lapras', 'http://www.serebii.net/pokemongo/pokemon/131.png').
image('ditto', 'http://www.serebii.net/pokemongo/pokemon/132.png').
image('eevee', 'http://www.serebii.net/pokemongo/pokemon/133.png').
image('vaporeon', 'http://www.serebii.net/pokemongo/pokemon/134.png').
image('jolteon', 'http://www.serebii.net/pokemongo/pokemon/135.png').
image('flareon', 'http://www.serebii.net/pokemongo/pokemon/136.png').
image('porygon', 'http://www.serebii.net/pokemongo/pokemon/137.png').
image('omanyte', 'http://www.serebii.net/pokemongo/pokemon/138.png').
image('omastar', 'http://www.serebii.net/pokemongo/pokemon/139.png').
image('kabuto', 'http://www.serebii.net/pokemongo/pokemon/140.png').
image('kabutops', 'http://www.serebii.net/pokemongo/pokemon/141.png').
image('aerodactyl', 'http://www.serebii.net/pokemongo/pokemon/142.png').
image('snorlax', 'http://www.serebii.net/pokemongo/pokemon/143.png').
image('articuno', 'http://www.serebii.net/pokemongo/pokemon/144.png').
image('zapdos', 'http://www.serebii.net/pokemongo/pokemon/145.png').
image('moltres', 'http://www.serebii.net/pokemongo/pokemon/146.png').
image('dratini', 'http://www.serebii.net/pokemongo/pokemon/147.png').
image('dragonair', 'http://www.serebii.net/pokemongo/pokemon/148.png').
image('dragonite', 'http://www.serebii.net/pokemongo/pokemon/149.png').
image('mewtwo', 'http://www.serebii.net/pokemongo/pokemon/150.png').
image('mew', 'http://www.serebii.net/pokemongo/pokemon/151.png').
